title: Coding for fun and profit
email: yanhui.zhao@outlook.com
description: >-
  This a blog site about different coding projects on various topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yzz127.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ""
github_username:  yzz127

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
